# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2274f10b86194ca37d8304cdc0ea8dd64042c3d6842d4bc6a44859abc5aa6588f129bcb012c5314ccf28169db1d2955cdf459b50eefc3f8bfb197300433d5128

test:
  secret_key_base: 62cb3515c9fe95a053a97b5c3e5ac86f2adf78ad4872413ede71ed871ba9d62ca008eb21cdb7369f17d0890ef2804c12d4f669945716d92ab0e4668abb281431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
